site_name: Web-программирование
site_url: https://KlimVladMaks.github.io/ITMO_ICT_WebDevelopment_2024-2025/
site_author: Владислав Клименков

theme:
  name: material
  language: ru

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

plugins:
  - glightbox

nav:
  - Главная: index.md
  - ЛР №1:
    - Задание 1: lab_1/task_1.md
    - Задание 2: lab_1/task_2.md
    - Задание 3: lab_1/task_3.md
    - Задание 4: lab_1/task_4.md
    - Задание 5: lab_1/task_5.md
  - ЛР №2:
    - Практическая работа №2.1: lab_2/pw_1.md
    - Практическая работа №2.2: lab_2/pw_2.md
    - Практическая работа №2.3: lab_2/pw_3.md
    - Лабораторная работа: lab_2/lw.md
  - ЛР №3:
    - Практическая работа №3.1: lab_3/pw_1.md
    - Практическая работа №3.2: lab_3/pw_2.md
    - Модель БД: lab_3/db_model.md
    - Лабораторная работа: lab_3/lw.md
    - Документация к API: lab_3/api_docs.md
